### ISSUE TITLE
.\padcheck.go:134:4: unknown field 'PaddingMode' in struct literal of type tls.Config

### ISSUE THREAD

**Issue by tfrist** [Tripwire/padcheck#3]
Hi Tripwire,

I tried build it using "go build", but unfortunately I got this error message as below.

.\padcheck.go:134:4: unknown field 'PaddingMode' in struct literal of type tls.Config

I googled but got nothing useful. I also checked the definition of tls.Config, it does not have a member named "PaddingMode". anything recommend? thanks.

btw, I comment that line and built an exe, but seems it does not work well for me.

**Comment by bespokebob** [comment]
You have to build a patched version of go to build the tool. You can use either the included Dockerfile to build it, or the build.sh script.

**Comment by tfrist** [comment]
Thanks Bob.
